version: 2

sources:
  - name: zeek
    database: vast
    schema: "{{ env_var('VASTDB_ZEEK_BUCKET') }}|{{ env_var('VASTDB_ZEEK_SCHEMA') }}"
    tables:
      - name: zeek_weird
        identifier: "{{ env_var('VASTDB_ZEEK_TABLE_PREFIX') }}weird"
      - name: zeek_known_hosts
      - name: zeek_http
      - name: zeek_conn
      - name: zeek_analyzer
      - name: zeek_ftp
      - name: zeek_dns
