version: 2

sources:
  - name: zeek
    database: vast
    schema: "{{ env_var('VASTDB_ZEEK_BUCKET') }}|{{ env_var('VASTDB_ZEEK_SCHEMA') }}"
    tables:
      - name: zeek_weird
        identifier: "{{ env_var('VASTDB_ZEEK_TABLE_PREFIX') }}weird"
      - name: zeek_known_hosts
        identifier: "{{ env_var('VASTDB_ZEEK_TABLE_PREFIX') }}known_hosts"
      - name: zeek_http
        identifier: "{{ env_var('VASTDB_ZEEK_TABLE_PREFIX') }}http"
      - name: zeek_conn
        identifier: "{{ env_var('VASTDB_ZEEK_TABLE_PREFIX') }}conn"
      - name: zeek_analyzer
        identifier: "{{ env_var('VASTDB_ZEEK_TABLE_PREFIX') }}analyzer"
      - name: zeek_ftp
        identifier: "{{ env_var('VASTDB_ZEEK_TABLE_PREFIX') }}ftp"
      - name: zeek_dns
        identifier: "{{ env_var('VASTDB_ZEEK_TABLE_PREFIX') }}dns"

  - name: fluentd
    database: vast
    schema: "{{ env_var('VASTDB_FLUENTD_BUCKET') }}|{{ env_var('VASTDB_FLUENTD_SCHEMA') }}"
    tables:
      - name: fluentd_file_system_activity
        identifier: "{{ env_var('VASTDB_FLUENTD_TABLE_PREFIX') }}file_system_activity"
      - name: fluentd_authentication
        identifier: "{{ env_var('VASTDB_FLUENTD_TABLE_PREFIX') }}authentication"
      - name: fluentd_detection_finding
        identifier: "{{ env_var('VASTDB_FLUENTD_TABLE_PREFIX') }}detection_finding"
